const LOGOUT = "LOGOUT";
const AUTH_ERROR = "AUTH_ERROR";
const CREATE_PROGRAM = "CREATE_PROGRAM";
const FETCH_PROGRAMS = "FETCH_PROGRAMS";
const FETCH_PROGRAM = "FETCH_PROGRAM";
const FETCH_MYPROGRAMS = "FETCH_MYPROGRAMS";

export {
  AUTH_ERROR,
  LOGOUT,
  CREATE_PROGRAM,
  FETCH_PROGRAMS,
  FETCH_PROGRAM,
  FETCH_MYPROGRAMS,
};
